### PR TITLE
WLBasicAnalogControl: Fix gyro mappings, plot input on curve

### PR DESCRIPTION
**Pull request by mkaito**
This does three things:

* The gyro axis mappings were wrong. Fixed them.
* Added a "ThrustHorizontal" command, useful for HOSAS (two sticks) setups. It's backwards and forward on the same axis.
* Put the gyro override value on a simple cubic curve, to make it easier to rotate slowly.

Also, VS2019 decided to "clean" the document and apply some code style, no idea why or how to prevent it from doing that, this is literally the first time I use VS2019. Diff is messy because of that, sorry.

Now I just need to figure out how to map joystick buttons to things...

### CODE REVIEW

**Comment by mkaito** [comment]
Oh yeah, and the script never actually gets called. Had to set it to Update1. Not sure why that is.

**Comment by mkaito** [comment]
Updated with a simplistic thrust model in order to account for gravity when adjusting vertical thrust. Setting it naively results in the grid dropping like a rock in gravity.

**Comment by mkaito** [comment]
`UpdateType.Mod` triggers on a local debug build of the plugin, but not with the version the PluginLoader gets from github. I've restored the guard either way. You'll have to talk to Austin about it, I don't know what's up with that.

**Comment by mkaito** [comment]
Sorry for mashing it all into one PR. I'll try to clean it up next week so you have an easier time reviewing it.

I've made the plugin support drones without a cockpit too, by swapping `IMyCockpit` to `IMyShipController`. A release build of this branch does correctly trigger PBs as well, unlike the version currently published via PluginLoader, just to confirm.

**Comment by mkaito** [comment]
Bit of a snag I noticed: the vertical thrust control works great... when you're level. If you pitch down and even just graze the throttle control, you dive like a rock. Fixing that will take some more work, as I need to work out angles affect effective thrust...

**Comment by matpratta** [comment]
Hey @mkaito sorry for the long delay, I took a few weeks off SE and GitHub in general.

I tried merging your changes but couldn't build them locally, seems VS gets angry at the removal of MDK (which makes sense). Could you please verify? Other than that your script seems really cool and has a ton more features than I expected before :D

Also, I've moved the sample scripts to [this repo](https://github.com/wolfe-labs/SE-AnalogThrottleScripts) so that things are more organized. If you want, feel free to make it as your own sample script and send a PR there, so I can include it! Would be nice to have both my basic version and yours there for comparison!

I will be closing this PR but feel free to comment in case you need :)

Thanks!

**Pull request closed without merging**
